#!/bin/bash

mkdir -p tap

. functions

tests="text render symbol leafs bits my_str"

for t in $tests; do
    tmp=$(build_tap t/$t.c)
    [ $? -eq 0 ] || echo $t
    echo "$tmp" | grep "^not ok" && echo $t.
done
